Repository softeerbootcamp-3rd/Team7-FiveGuys, pull requests merged in 2024-02, with the labels that each got.

#33 [BE] Response 및 공통 예외 처리 구현
  BE/robocar/src/main/java/com/fiveguys/robocar/apiPayload/GeneralExceptionHandler.java
  BE/robocar/src/main/java/com/fiveguys/robocar/apiPayload/ResponseApi.java
  BE/robocar/src/main/java/com/fiveguys/robocar/apiPayload/ResponseStatus.java
  BE/robocar/src/main/java/com/fiveguys/robocar/apiPayload/exception/GeneralException.java
  BE/robocar/src/main/java/com/fiveguys/robocar/service/TestService.java
  BE/robocar/src/main/java/com/fiveguys/robocar/service/TestServiceImpl.java
  BE/robocar/src/main/java/com/fiveguys/robocar/swaggertest/ExampleController.java
Labels: 🌱 Feat

#32 Be/feat/entity(#8)
  BE/robocar/src/main/java/com/fiveguys/robocar/entity/Car.java
  BE/robocar/src/main/java/com/fiveguys/robocar/entity/Garage.java
  BE/robocar/src/main/java/com/fiveguys/robocar/entity/InOperation.java
  BE/robocar/src/main/java/com/fiveguys/robocar/entity/User.java
  BE/robocar/src/main/java/com/fiveguys/robocar/models/CarState.java
  BE/robocar/src/main/java/com/fiveguys/robocar/models/Gender.java
  BE/robocar/src/main/java/com/fiveguys/robocar/repository/CarRepository.java
  BE/robocar/src/main/java/com/fiveguys/robocar/repository/GarageRepository.java
  BE/robocar/src/main/java/com/fiveguys/robocar/repository/InOperationRepository.java
  BE/robocar/src/main/java/com/fiveguys/robocar/repository/UserRepository.java
Labels: 🌱 Feat

#34 [AOS] 홈 화면 레이아웃 구현
  AOS/app/build.gradle.kts
  AOS/app/src/main/AndroidManifest.xml
  AOS/app/src/main/java/org/softeer/robocar/ui/activity/HomeActivity.kt
  AOS/app/src/main/java/org/softeer/robocar/ui/fragment/HomeFragment.kt
  AOS/app/src/main/java/org/softeer/robocar/ui/fragment/MyPageFragment.kt
  AOS/app/src/main/java/org/softeer/robocar/utils/ActivityExtensions.kt
  AOS/app/src/main/res/color/menu_selector_color.xml
  AOS/app/src/main/res/drawable/icon_nav_my_page.xml
  AOS/app/src/main/res/drawable/icon_nav_my_page_blue.xml
  AOS/app/src/main/res/drawable/icon_nav_my_page_gray.xml
  AOS/app/src/main/res/drawable/rectangle_active_blue_pms_312c_radius_30.xml
  AOS/app/src/main/res/drawable/rectangle_hyundai_blue_radius_30.xml
  AOS/app/src/main/res/drawable/rectangle_sky_blue_pms_radius_30.xml
  AOS/app/src/main/res/drawable/rectangle_yellow_200_radius_30.xml
  AOS/app/src/main/res/font/pretendard_semibold.otf
  AOS/app/src/main/res/layout/activity_home.xml
  AOS/app/src/main/res/layout/fragment_home.xml
  AOS/app/src/main/res/layout/fragment_my_page.xml
  AOS/app/src/main/res/menu/bottom_navigation_menu.xml
  AOS/app/src/main/res/navigation/nav_graph.xml
  AOS/app/src/main/res/values/colors.xml
  AOS/app/src/main/res/values/strings.xml
  AOS/app/src/main/res/values/styles.xml
  AOS/app/src/main/res/values/themes.xml
Labels: 🌱 Feat

#36 [AOS] 마이페이지 레이아웃 구현
  AOS/app/src/main/res/drawable/icon_arrow_right.xml
  AOS/app/src/main/res/layout/fragment_my_page.xml
  AOS/app/src/main/res/values/strings.xml
Labels: 🌱 Feat

#37 [AOS] 로그인 레이아웃 구현
  AOS/app/src/main/AndroidManifest.xml
  AOS/app/src/main/java/org/softeer/robocar/ui/activity/LoginActivity.kt
  AOS/app/src/main/java/org/softeer/robocar/ui/custom/BackPressClearFocusEditText.kt
  AOS/app/src/main/res/drawable/rectangle_gray_150_radius_12.xml
  AOS/app/src/main/res/layout/activity_login.xml
  AOS/app/src/main/res/values/colors.xml
  AOS/app/src/main/res/values/strings.xml
Labels: 🌱 Feat

#39 [AOS] activity_map layout
  AOS/app/build.gradle.kts
  AOS/app/src/main/AndroidManifest.xml
  AOS/app/src/main/java/org/softeer/robocar/ui/activity/MapActivity.kt
  AOS/app/src/main/res/layout/activity_map.xml
  AOS/settings.gradle.kts
Labels: 🌱 Feat

#40 [AOS] 차량 호출 로딩페이지 레이아웃 구현
  AOS/app/src/main/AndroidManifest.xml
  AOS/app/src/main/java/org/softeer/robocar/ui/activity/LoadingActivity.kt
  AOS/app/src/main/java/org/softeer/robocar/ui/fragment/CarPoolCallFragment.kt
  AOS/app/src/main/java/org/softeer/robocar/ui/fragment/CarPoolMatchingFragment.kt
  AOS/app/src/main/java/org/softeer/robocar/ui/fragment/TaxiCallFragment.kt
  AOS/app/src/main/res/drawable/img_horizontal_move_car.xml
  AOS/app/src/main/res/drawable/img_vertical_move_car.xml
  AOS/app/src/main/res/layout/activity_loading.xml
  AOS/app/src/main/res/layout/fragment_car_pool_call.xml
  AOS/app/src/main/res/layout/fragment_car_pool_matching.xml
  AOS/app/src/main/res/layout/fragment_taxi_call.xml
  AOS/app/src/main/res/values/strings.xml
Labels: 🌱 Feat

#43 [BE] CICD 구현
  BE/robocar/.gitignore
  appspec.yml
  scripts/deploy.sh
Labels: 🔧 Build

#35 [BE] Redis 연동 및 테스트
  BE/robocar/build.gradle
  BE/robocar/src/main/java/com/fiveguys/robocar/entity/CarpoolRequest.java
  BE/robocar/src/main/java/com/fiveguys/robocar/models/CarState.java
  BE/robocar/src/main/java/com/fiveguys/robocar/models/Gender.java
  BE/robocar/src/main/java/com/fiveguys/robocar/repository/CarpoolRequestRepository.java
  BE/robocar/src/main/java/com/fiveguys/robocar/service/CarpoolRequestService.java
  BE/robocar/src/test/java/com/fiveguys/robocar/service/CarpoolRequestServiceTest.java
Labels: 🌱 Feat

#41 [AOS] 동승 요청(수신) 다이얼로그 레이아웃 구현
  AOS/app/src/main/java/org/softeer/robocar/ui/fragment/ReceivedCarPoolRequestDialogFragment.kt
  AOS/app/src/main/res/layout/fragment_dialog_received_car_pool_request.xml
  AOS/app/src/main/res/values/strings.xml
Labels: 🌱 Feat

#42 [AOS] 동승 요청(발신) 다이얼로그 레이아웃 구현
  AOS/app/src/main/java/org/softeer/robocar/ui/fragment/CarPoolRequestDialogFragment.kt
  AOS/app/src/main/res/layout/fragment_dialog_car_pool_request.xml
  AOS/app/src/main/res/values/strings.xml
Labels: 🌱 Feat

#44 [AOS] 동승 불가능 레이아웃 구현
  AOS/app/src/main/AndroidManifest.xml
  AOS/app/src/main/java/org/softeer/robocar/ui/activity/RequestCarPoolActivity.kt
  AOS/app/src/main/java/org/softeer/robocar/ui/fragment/NoAvailableCarPoolFragment.kt
  AOS/app/src/main/res/drawable/icon_arrow_left.xml
  AOS/app/src/main/res/layout/activity_request_car_pool.xml
  AOS/app/src/main/res/layout/fragment_no_available_car_pool.xml
  AOS/app/src/main/res/values/strings.xml
Labels: 🌱 Feat

#45 [AOS] HeadcountDialogFragment 제작
  AOS/app/src/main/AndroidManifest.xml
  AOS/app/src/main/java/org/softeer/robocar/ui/activity/MapActivity.kt
  AOS/app/src/main/java/org/softeer/robocar/ui/fragment/HeadcountDialogFragment.kt
  AOS/app/src/main/res/drawable/img_minus.xml
  AOS/app/src/main/res/drawable/img_plus.xml
  AOS/app/src/main/res/layout/activity_map.xml
  AOS/app/src/main/res/layout/fragment_headcount_dialog.xml
  AOS/app/src/main/res/navigation/nav_graph.xml
  AOS/app/src/main/res/values/strings.xml
Labels: 🌱 Feat

#50 [BE] Garage API 구현
  BE/robocar/src/main/java/com/fiveguys/robocar/apiPayload/ResponseApi.java
  BE/robocar/src/main/java/com/fiveguys/robocar/apiPayload/ResponseStatus.java
  BE/robocar/src/main/java/com/fiveguys/robocar/controller/GarageController.java
  BE/robocar/src/main/java/com/fiveguys/robocar/dto/req/GarageReqDto.java
  BE/robocar/src/main/java/com/fiveguys/robocar/entity/Garage.java
  BE/robocar/src/main/java/com/fiveguys/robocar/repository/GarageRepository.java
  BE/robocar/src/main/java/com/fiveguys/robocar/service/GarageService.java
  BE/robocar/src/test/java/com/fiveguys/robocar/service/GarageServiceTest.java
Labels: 🌱 Feat

#53 [AOS] 동승 가능 차량 리스트 레이아웃 구현
  AOS/app/src/main/java/org/softeer/robocar/data/model/CarPool.kt
  AOS/app/src/main/java/org/softeer/robocar/ui/adapter/CarPoolAdapter.kt
  AOS/app/src/main/java/org/softeer/robocar/ui/custom/MarginItemDecoration.kt
  AOS/app/src/main/java/org/softeer/robocar/ui/fragment/CarPoolListFragment.kt
  AOS/app/src/main/res/drawable/icon_arrow_down.xml
  AOS/app/src/main/res/layout/fragment_car_pool_detail.xml
  AOS/app/src/main/res/layout/fragment_car_pool_item.xml
  AOS/app/src/main/res/layout/fragment_car_pool_list.xml
  AOS/app/src/main/res/values/strings.xml
Labels: 🌱 Feat

#49 [AOS] 회원가입관련 레이아웃 구현
  AOS/app/src/main/java/org/softeer/robocar/ui/activity/ModifyPasswordActivity.kt
  AOS/app/src/main/java/org/softeer/robocar/ui/activity/ModifyUserActivity.kt
  AOS/app/src/main/java/org/softeer/robocar/ui/activity/RegisterActivity.kt
  AOS/app/src/main/res/layout/activity_modify_password.xml
  AOS/app/src/main/res/layout/activity_modify_user.xml
  AOS/app/src/main/res/layout/activity_register.xml
  AOS/app/src/main/res/values/dimens.xml
  AOS/app/src/main/res/values/strings.xml
Labels: 🌱 Feat

#51 [BE] JWT관련 로직 구현
  BE/robocar/build.gradle
  BE/robocar/src/main/java/com/fiveguys/robocar/config/FilterConfig.java
  BE/robocar/src/main/java/com/fiveguys/robocar/entity/User.java
  BE/robocar/src/main/java/com/fiveguys/robocar/filter/JwtRequestFilter.java
  BE/robocar/src/main/java/com/fiveguys/robocar/util/JwtUtil.java
  BE/robocar/src/test/java/com/fiveguys/robocar/util/JwtUtilTest.java
Labels: 🌱 Feat

#52 [BE] 지도 API 통신확인 및 연동
  BE/robocar/build.gradle
  BE/robocar/src/main/java/com/fiveguys/robocar/apiPayload/ResponseStatus.java
  BE/robocar/src/main/java/com/fiveguys/robocar/config/RestClientConfig.java
  BE/robocar/src/main/java/com/fiveguys/robocar/service/MapService.java
  BE/robocar/src/main/java/com/fiveguys/robocar/service/RouteComparisonService.java
  BE/robocar/src/main/java/com/fiveguys/robocar/service/RouteService.java
  BE/robocar/src/main/java/com/fiveguys/robocar/util/JsonParserUtil.java
  BE/robocar/src/test/java/com/fiveguys/robocar/RobocarApplicationTests.java
  BE/robocar/src/test/java/com/fiveguys/robocar/service/MapServiceTest.java
  BE/robocar/src/test/java/com/fiveguys/robocar/service/RouteComparisonServiceTest.java
  BE/robocar/src/test/java/com/fiveguys/robocar/service/RouteServiceTest.java
Labels: 🌱 Feat

#74 [Fix] UserId가 안고쳐진 부분 추가 수정
  BE/robocar/src/main/java/com/fiveguys/robocar/entity/User.java
  BE/robocar/src/main/java/com/fiveguys/robocar/filter/JwtRequestFilter.java
  BE/robocar/src/main/java/com/fiveguys/robocar/util/JwtUtil.java
  BE/robocar/src/test/java/com/fiveguys/robocar/util/JwtUtilTest.java
Labels: 🛠️ Fix

#75 [Fix] JWT 예외 처리 추가
  BE/robocar/src/main/java/com/fiveguys/robocar/filter/JwtRequestFilter.java
Labels: 🛠️ Fix

#64 [AOS] 앱 아이콘, 스플래시 설정
  AOS/app/src/main/res/drawable/ic_launcher_foreground.xml
  AOS/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  AOS/app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  AOS/app/src/main/res/mipmap-hdpi/ic_launcher.webp
  AOS/app/src/main/res/mipmap-hdpi/ic_launcher_background.webp
  AOS/app/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  AOS/app/src/main/res/mipmap-mdpi/ic_launcher.webp
  AOS/app/src/main/res/mipmap-mdpi/ic_launcher_background.webp
  AOS/app/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  AOS/app/src/main/res/mipmap-xhdpi/ic_launcher.webp
  AOS/app/src/main/res/mipmap-xhdpi/ic_launcher_background.webp
  AOS/app/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  AOS/app/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  AOS/app/src/main/res/mipmap-xxhdpi/ic_launcher_background.webp
  AOS/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  AOS/app/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  AOS/app/src/main/res/mipmap-xxxhdpi/ic_launcher_background.webp
  AOS/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
  AOS/app/src/main/res/values/ic_launcher_background.xml
  AOS/app/src/main/res/values/themes.xml
Labels: 🌱 Feat

#72 [BE] 토스 결제 API 구현
  BE/robocar/build.gradle
  BE/robocar/src/main/java/com/fiveguys/robocar/apiPayload/ResponseApi.java
  BE/robocar/src/main/java/com/fiveguys/robocar/apiPayload/ResponseStatus.java
  BE/robocar/src/main/java/com/fiveguys/robocar/config/TossPaymentConfig.java
  BE/robocar/src/main/java/com/fiveguys/robocar/controller/GarageController.java
  BE/robocar/src/main/java/com/fiveguys/robocar/controller/PaymentController.java
  BE/robocar/src/main/java/com/fiveguys/robocar/converter/PaymentConverter.java
  BE/robocar/src/main/java/com/fiveguys/robocar/dto/PaymentFailDto.java
  BE/robocar/src/main/java/com/fiveguys/robocar/dto/PaymentSuccessCardDto.java
  BE/robocar/src/main/java/com/fiveguys/robocar/dto/PaymentSuccessDto.java
  BE/robocar/src/main/java/com/fiveguys/robocar/dto/req/GarageReqDto.java
  BE/robocar/src/main/java/com/fiveguys/robocar/dto/req/PaymentReqDto.java
  BE/robocar/src/main/java/com/fiveguys/robocar/dto/res/PaymentResDto.java
  BE/robocar/src/main/java/com/fiveguys/robocar/entity/Payment.java
  BE/robocar/src/main/java/com/fiveguys/robocar/models/PayType.java
  BE/robocar/src/main/java/com/fiveguys/robocar/models/TossPaymentConstants.java
  BE/robocar/src/main/java/com/fiveguys/robocar/repository/PaymentRepository.java
  BE/robocar/src/main/java/com/fiveguys/robocar/service/GarageService.java
  BE/robocar/src/main/java/com/fiveguys/robocar/service/PaymentService.java
Labels: 🌱 Feat

#58 [BE] Car Api 구현
  BE/robocar/build.gradle
  BE/robocar/src/main/java/com/fiveguys/robocar/apiPayload/ResponseStatus.java
  BE/robocar/src/main/java/com/fiveguys/robocar/controller/CarController.java
  BE/robocar/src/main/java/com/fiveguys/robocar/dto/RouteInfo.java
  BE/robocar/src/main/java/com/fiveguys/robocar/dto/req/CarReqDto.java
  BE/robocar/src/main/java/com/fiveguys/robocar/entity/Car.java
  BE/robocar/src/main/java/com/fiveguys/robocar/repository/CarRepository.java
  BE/robocar/src/main/java/com/fiveguys/robocar/service/CarService.java
  BE/robocar/src/main/java/com/fiveguys/robocar/service/MapService.java
  BE/robocar/src/main/java/com/fiveguys/robocar/service/RouteComparisonService.java
  BE/robocar/src/main/java/com/fiveguys/robocar/service/RouteService.java
  BE/robocar/src/test/java/com/fiveguys/robocar/service/MapServiceTest.java
  BE/robocar/src/test/java/com/fiveguys/robocar/service/RouteComparisonServiceTest.java
  BE/robocar/src/test/java/com/fiveguys/robocar/service/RouteServiceTest.java
Labels: 🌱 Feat

#77 [AOS] 동승 가능 차량 상세정보 페이지 API 데이터 연동
  AOS/app/build.gradle.kts
  AOS/app/src/main/java/org/softeer/robocar/data/mapper/CarPoolInfoMapper.kt
  AOS/app/src/main/java/org/softeer/robocar/data/model/CarPool.kt
  AOS/app/src/main/java/org/softeer/robocar/ui/activity/RequestCarPoolActivity.kt
  AOS/app/src/main/java/org/softeer/robocar/ui/adapter/CarPoolAdapter.kt
  AOS/app/src/main/java/org/softeer/robocar/ui/adapter/CarPoolBindingAdapter.kt
  AOS/app/src/main/java/org/softeer/robocar/ui/adapter/CarPoolListClickListener.kt
  AOS/app/src/main/java/org/softeer/robocar/ui/fragment/CarPoolListFragment.kt
  AOS/app/src/main/java/org/softeer/robocar/ui/fragment/CarPoolRequestDetailFragment.kt
  AOS/app/src/main/java/org/softeer/robocar/ui/viewmodel/CarPoolDetailViewModel.kt
  AOS/app/src/main/java/org/softeer/robocar/utils/TimeExtensions.kt
  AOS/app/src/main/res/drawable/rectangle_gray_600_radius_12.xml
  AOS/app/src/main/res/drawable/rectangle_hyundai_blue_radius_12.xml
  AOS/app/src/main/res/layout/activity_request_car_pool.xml
  AOS/app/src/main/res/layout/fragment_car_pool_detail.xml
  AOS/app/src/main/res/layout/fragment_car_pool_list.xml
  AOS/app/src/main/res/navigation/request_car_pool_nav_graph.xml
  AOS/app/src/main/res/raw/loading.json
  AOS/build.gradle.kts
Labels: 🌱 Feat

#81 [BE] JWT 로직 버그 해결 및 리팩토링
  BE/robocar/src/main/java/com/fiveguys/robocar/config/FilterConfig.java
  BE/robocar/src/main/java/com/fiveguys/robocar/config/SwaggerConfig.java
  BE/robocar/src/main/java/com/fiveguys/robocar/config/WebConfig.java
  BE/robocar/src/main/java/com/fiveguys/robocar/controller/AuthRequestMappingScanner.java
  BE/robocar/src/main/java/com/fiveguys/robocar/controller/JwtController.java
  BE/robocar/src/main/java/com/fiveguys/robocar/controller/PaymentController.java
  BE/robocar/src/main/java/com/fiveguys/robocar/controller/annotation/Auth.java
  BE/robocar/src/main/java/com/fiveguys/robocar/controller/resolver/AuthArgumentResolver.java
  BE/robocar/src/main/java/com/fiveguys/robocar/filter/JwtAuthenticationFilter.java
  BE/robocar/src/main/java/com/fiveguys/robocar/filter/JwtRequestFilter.java
  BE/robocar/src/main/java/com/fiveguys/robocar/models/LoginConstant.java
  BE/robocar/src/main/java/com/fiveguys/robocar/models/TokenConstant.java
  BE/robocar/src/main/java/com/fiveguys/robocar/service/GarageService.java
  BE/robocar/src/main/java/com/fiveguys/robocar/util/JwtUtil.java
Labels: 🌱 Feat, 🛠️ Fix, ✂️ Refactor

#83 [AOS] Map Activity의 bottom sheet와 내부 구성 fragment의 layout 구성
  AOS/app/src/main/AndroidManifest.xml
  AOS/app/src/main/java/org/softeer/robocar/ui/activity/MapActivity.kt
  AOS/app/src/main/java/org/softeer/robocar/ui/fragment/HeadcountDialogFragment.kt
  AOS/app/src/main/java/org/softeer/robocar/ui/fragment/InternalControlFragment.kt
  AOS/app/src/main/java/org/softeer/robocar/ui/fragment/PathSettingFragment.kt
  AOS/app/src/main/java/org/softeer/robocar/ui/fragment/SelectDestinationFragment.kt
  AOS/app/src/main/java/org/softeer/robocar/utils/ActivityExtensions.kt
  AOS/app/src/main/res/color/track_air_conditioner_toggle.xml
  AOS/app/src/main/res/drawable/icon_hamburger.xml
  AOS/app/src/main/res/drawable/img_air_conditioner.xml
  AOS/app/src/main/res/drawable/img_btn_heating.xml
  AOS/app/src/main/res/drawable/img_btn_seat.xml
  AOS/app/src/main/res/drawable/img_btn_ventilation.xml
  AOS/app/src/main/res/drawable/img_control0.xml
  AOS/app/src/main/res/drawable/img_control1.xml
  AOS/app/src/main/res/drawable/img_control2.xml
  AOS/app/src/main/res/drawable/img_control3.xml
  AOS/app/src/main/res/drawable/img_departure.xml
  AOS/app/src/main/res/drawable/img_heating_all.xml
  AOS/app/src/main/res/drawable/img_lock.xml
  AOS/app/src/main/res/drawable/img_off_all.xml
  AOS/app/src/main/res/drawable/img_seat.xml
  AOS/app/src/main/res/drawable/img_unlock.xml
  AOS/app/src/main/res/drawable/img_ventilation_all.xml
  AOS/app/src/main/res/drawable/rectangle_gray_200_radius_12.xml
  AOS/app/src/main/res/drawable/rectangle_white_top_radius_20.xml
  AOS/app/src/main/res/layout/activity_map.xml
  AOS/app/src/main/res/layout/fragment_headcount_dialog.xml
  AOS/app/src/main/res/layout/fragment_internal_control.xml
  AOS/app/src/main/res/layout/fragment_path_setting.xml
  AOS/app/src/main/res/layout/fragment_select_destination.xml
  AOS/app/src/main/res/navigation/nav_graph.xml
  AOS/app/src/main/res/values/strings.xml
  AOS/app/src/main/res/values/styles.xml
Labels: 🌱 Feat

#79 [BE] NaverMap 한글주소를 좌표로 변환하는 로직추가
  BE/robocar/src/main/java/com/fiveguys/robocar/apiPayload/ResponseStatus.java
  BE/robocar/src/main/java/com/fiveguys/robocar/config/NaverMapConfig.java
  BE/robocar/src/main/java/com/fiveguys/robocar/service/MapService.java
  BE/robocar/src/main/java/com/fiveguys/robocar/util/JsonParserUtil.java
  BE/robocar/src/test/java/com/fiveguys/robocar/service/MapServiceTest.java
Labels: 🌱 Feat

#88 [BE] JwtAuthenticationFIlter 버그 해결
  BE/robocar/src/main/java/com/fiveguys/robocar/auth/Auth.java
  BE/robocar/src/main/java/com/fiveguys/robocar/auth/AuthArgumentResolver.java
  BE/robocar/src/main/java/com/fiveguys/robocar/auth/AuthRequestMappingScanner.java
  BE/robocar/src/main/java/com/fiveguys/robocar/auth/RequestMappings.java
  BE/robocar/src/main/java/com/fiveguys/robocar/config/WebConfig.java
  BE/robocar/src/main/java/com/fiveguys/robocar/controller/JwtController.java
  BE/robocar/src/main/java/com/fiveguys/robocar/controller/PaymentController.java
  BE/robocar/src/main/java/com/fiveguys/robocar/filter/JwtAuthenticationFilter.java
Labels: 🛠️ Fix

#92 [BE] User API 구현
  BE/robocar/src/main/java/com/fiveguys/robocar/apiPayload/ResponseStatus.java
  BE/robocar/src/main/java/com/fiveguys/robocar/controller/UserController.java
  BE/robocar/src/main/java/com/fiveguys/robocar/dto/req/UserCreateReqDto.java
  BE/robocar/src/main/java/com/fiveguys/robocar/dto/req/UserLoginReqDto.java
  BE/robocar/src/main/java/com/fiveguys/robocar/dto/req/UserNicknameReqDto.java
  BE/robocar/src/main/java/com/fiveguys/robocar/dto/req/UserPasswordReqDto.java
  BE/robocar/src/main/java/com/fiveguys/robocar/dto/res/LoginResDto.java
  BE/robocar/src/main/java/com/fiveguys/robocar/entity/User.java
  BE/robocar/src/main/java/com/fiveguys/robocar/repository/UserRepository.java
  BE/robocar/src/main/java/com/fiveguys/robocar/service/UserService.java
  BE/robocar/src/test/java/com/fiveguys/robocar/entity/UserTest.java
Labels: 🌱 Feat

#90 [AOS] PR(#83) 피드백 반영 및 navigation 수정
  AOS/app/src/main/AndroidManifest.xml
  AOS/app/src/main/java/org/softeer/robocar/ui/fragment/HeadcountDialogFragment.kt
  AOS/app/src/main/java/org/softeer/robocar/ui/fragment/PathSettingFragment.kt
  AOS/app/src/main/java/org/softeer/robocar/ui/fragment/SelectDestinationFragment.kt
  AOS/app/src/main/res/layout/activity_home.xml
  AOS/app/src/main/res/layout/activity_map.xml
  AOS/app/src/main/res/layout/fragment_path_setting.xml
  AOS/app/src/main/res/navigation/bottom_sheet_nav_graph.xml
  AOS/app/src/main/res/navigation/home_nav_graph.xml
Labels: 🛠️ Fix, ✂️ Refactor

#101 [Fix] Response data값 수정
  BE/robocar/src/main/java/com/fiveguys/robocar/controller/UserController.java
  BE/robocar/src/main/java/com/fiveguys/robocar/dto/res/UserAvailableResDto.java
  BE/robocar/src/main/java/com/fiveguys/robocar/service/UserService.java
Labels: 🛠️ Fix

#103 [AOS] 회원가입 API 연동
  AOS/app/src/main/AndroidManifest.xml
  AOS/app/src/main/java/org/softeer/robocar/data/dto/user/request/SignUpRequest.kt
  AOS/app/src/main/java/org/softeer/robocar/data/dto/user/response/CheckAvailableNicknameResponse.kt
  AOS/app/src/main/java/org/softeer/robocar/data/dto/user/response/CheckAvailableUserIdResponse.kt
  AOS/app/src/main/java/org/softeer/robocar/data/model/CarPoolType.kt
  AOS/app/src/main/java/org/softeer/robocar/data/model/TaxiType.kt
  AOS/app/src/main/java/org/softeer/robocar/data/repository/user/UserRemoteDataSource.kt
  AOS/app/src/main/java/org/softeer/robocar/data/repository/user/UserRemoteDataSourceImpl.kt
  AOS/app/src/main/java/org/softeer/robocar/data/repository/user/UserRepository.kt
  AOS/app/src/main/java/org/softeer/robocar/data/repository/user/UserRepositoryImpl.kt
  AOS/app/src/main/java/org/softeer/robocar/data/service/user/UserService.kt
  AOS/app/src/main/java/org/softeer/robocar/di/DataSourceModule.kt
  AOS/app/src/main/java/org/softeer/robocar/di/RepositoryModule.kt
  AOS/app/src/main/java/org/softeer/robocar/di/ServiceModule.kt
  AOS/app/src/main/java/org/softeer/robocar/domain/usecase/CheckDuplicatedNicknameUseCase.kt
  AOS/app/src/main/java/org/softeer/robocar/domain/usecase/CheckDuplicatedUserIdUseCase.kt
  AOS/app/src/main/java/org/softeer/robocar/domain/usecase/SignUpUseCase.kt
  AOS/app/src/main/java/org/softeer/robocar/ui/activity/LoginActivity.kt
  AOS/app/src/main/java/org/softeer/robocar/ui/activity/RegisterActivity.kt
  AOS/app/src/main/java/org/softeer/robocar/ui/adapter/SignUpBindingAdapter.kt
  AOS/app/src/main/java/org/softeer/robocar/ui/fragment/HomeFragment.kt
  AOS/app/src/main/java/org/softeer/robocar/ui/viewmodel/SignUpViewModel.kt
  AOS/app/src/main/res/layout/activity_login.xml
  AOS/app/src/main/res/layout/activity_register.xml
  AOS/app/src/main/res/navigation/home_nav_graph.xml
Labels: 🌱 Feat

#107 [AOS] 출발,호스트도착,게스트도착지에 맞게 차량 배정 + 화면
  AOS/app/build.gradle.kts
  AOS/app/src/main/java/org/softeer/robocar/data/dto/route/response/RouteResponse.kt
  AOS/app/src/main/java/org/softeer/robocar/data/mapper/RouteInfoMapper.kt
  AOS/app/src/main/java/org/softeer/robocar/data/model/Route.kt
  AOS/app/src/main/java/org/softeer/robocar/data/repository/route/RouteRemoteDataSource.kt
  AOS/app/src/main/java/org/softeer/robocar/data/repository/route/RouteRemoteDataSourceImpl.kt
  AOS/app/src/main/java/org/softeer/robocar/data/repository/route/RouteRepository.kt
  AOS/app/src/main/java/org/softeer/robocar/data/repository/route/RouteRepositoryImpl.kt
  AOS/app/src/main/java/org/softeer/robocar/data/service/route/RouteService.kt
  AOS/app/src/main/java/org/softeer/robocar/di/DataSourceModule.kt
  AOS/app/src/main/java/org/softeer/robocar/di/RepositoryModule.kt
  AOS/app/src/main/java/org/softeer/robocar/di/ServiceModule.kt
  AOS/app/src/main/java/org/softeer/robocar/domain/usecase/GetOptimizedRouteUseCase.kt
  AOS/app/src/main/java/org/softeer/robocar/ui/activity/MapActivity.kt
  AOS/app/src/main/java/org/softeer/robocar/ui/adapter/RouteBindingAdapert.kt
  AOS/app/src/main/java/org/softeer/robocar/ui/fragment/TaxiInformationFragment.kt
  AOS/app/src/main/java/org/softeer/robocar/ui/viewmodel/RouteViewModel.kt
  AOS/app/src/main/res/layout/activity_map.xml
  AOS/app/src/main/res/layout/fragment_taxi_information.xml
Labels: 🌱 Feat

#112 [BE] Carpool List Up 구현
  BE/robocar/src/main/java/com/fiveguys/robocar/apiPayload/ResponseStatus.java
  BE/robocar/src/main/java/com/fiveguys/robocar/controller/OperationController.java
  BE/robocar/src/main/java/com/fiveguys/robocar/models/CarType.java
  BE/robocar/src/main/java/com/fiveguys/robocar/service/OperationService.java
  BE/robocar/src/main/java/com/fiveguys/robocar/util/CreateCarpoolListUpResDto.java
  BE/robocar/src/test/java/com/fiveguys/robocar/service/MapServiceTest.java
  BE/robocar/src/test/java/com/fiveguys/robocar/service/OperationServiceTest.java
Labels: 🌱 Feat

#113 [BE] FCM API 구현
  BE/robocar/build.gradle
  BE/robocar/src/main/java/com/fiveguys/robocar/config/FCMConfig.java
  BE/robocar/src/main/java/com/fiveguys/robocar/controller/FcmController.java
  BE/robocar/src/main/java/com/fiveguys/robocar/dto/req/CarpoolRequestDTO.java
  BE/robocar/src/main/java/com/fiveguys/robocar/models/FcmMessage.java
  BE/robocar/src/main/java/com/fiveguys/robocar/models/FcmNotificationType.java
  BE/robocar/src/main/java/com/fiveguys/robocar/service/FirebaseCloudMessageService.java
  BE/robocar/src/main/java/com/fiveguys/robocar/service/PaymentService.java
Labels: 🌱 Feat

#105 [BE] OperationController 구현 및 /oprations/optimized-route api 완성
  BE/robocar/build.gradle
  BE/robocar/src/main/java/com/fiveguys/robocar/apiPayload/ResponseStatus.java
  BE/robocar/src/main/java/com/fiveguys/robocar/controller/CarController.java
  BE/robocar/src/main/java/com/fiveguys/robocar/controller/OperationController.java
  BE/robocar/src/main/java/com/fiveguys/robocar/dto/res/RouteResDto.java
  BE/robocar/src/main/java/com/fiveguys/robocar/repository/CarRepository.java
  BE/robocar/src/main/java/com/fiveguys/robocar/service/CarService.java
  BE/robocar/src/main/java/com/fiveguys/robocar/service/GarageService.java
  BE/robocar/src/main/java/com/fiveguys/robocar/service/OperationService.java
  BE/robocar/src/main/java/com/fiveguys/robocar/service/RouteService.java
  BE/robocar/src/main/java/com/fiveguys/robocar/util/JsonParserUtil.java
Labels: 🌱 Feat

#106 [BE] 로그인시 FCM토큰 저장
  BE/robocar/src/main/java/com/fiveguys/robocar/dto/req/UserLoginReqDto.java
  BE/robocar/src/main/java/com/fiveguys/robocar/entity/User.java
  BE/robocar/src/main/java/com/fiveguys/robocar/service/UserService.java
Labels: 🌱 Feat

#119 [BE] fcm push되는 데이터 및 리턴값 수정
  BE/robocar/src/main/java/com/fiveguys/robocar/controller/FcmController.java
  BE/robocar/src/main/java/com/fiveguys/robocar/models/FcmMessage.java
  BE/robocar/src/main/java/com/fiveguys/robocar/service/FirebaseCloudMessageService.java
Labels: 🌱 Feat, ✂️ Refactor

#122 [Chore] 최적경로 로직수정
  BE/robocar/src/main/java/com/fiveguys/robocar/service/OperationService.java
Labels: 🛠️ Fix

#123 [BE] Operations Controller의 동승 요청, 동승 거절 API 구현
  BE/robocar/src/main/java/com/fiveguys/robocar/controller/CarController.java
  BE/robocar/src/main/java/com/fiveguys/robocar/controller/FcmController.java
  BE/robocar/src/main/java/com/fiveguys/robocar/controller/OperationController.java
  BE/robocar/src/main/java/com/fiveguys/robocar/dto/req/CarpoolRequestDto.java
  BE/robocar/src/main/java/com/fiveguys/robocar/models/CarState.java
  BE/robocar/src/main/java/com/fiveguys/robocar/models/FcmMessage.java
  BE/robocar/src/main/java/com/fiveguys/robocar/service/FirebaseCloudMessageService.java
Labels: 🌱 Feat

#129 [AOS] 검색 기능 구현 및 map activity 내에서 탑승 유형 데이터 전송
  AOS/app/build.gradle.kts
  AOS/app/src/main/java/org/softeer/robocar/data/dto/placesearch/PlaceSearchResponse.kt
  AOS/app/src/main/java/org/softeer/robocar/data/model/PlaceItem.kt
  AOS/app/src/main/java/org/softeer/robocar/data/repository/PlaceSearch/PlaceSearchRemoteDataSource.kt
  AOS/app/src/main/java/org/softeer/robocar/data/repository/PlaceSearch/PlaceSearchRemoteDataSourceImpl.kt
  AOS/app/src/main/java/org/softeer/robocar/data/repository/PlaceSearch/PlaceSearchRepository.kt
  AOS/app/src/main/java/org/softeer/robocar/data/repository/PlaceSearch/PlaceSearchRepositoryImpl.kt
  AOS/app/src/main/java/org/softeer/robocar/data/service/PlaceSearch/PlaceSearchService.kt
  AOS/app/src/main/java/org/softeer/robocar/di/DataSourceModule.kt
  AOS/app/src/main/java/org/softeer/robocar/di/NetworkModule.kt
  AOS/app/src/main/java/org/softeer/robocar/di/RepositoryModule.kt
  AOS/app/src/main/java/org/softeer/robocar/di/ServiceModule.kt
  AOS/app/src/main/java/org/softeer/robocar/domain/usecase/SearchPlaceUseCase.kt
  AOS/app/src/main/java/org/softeer/robocar/ui/activity/MapActivity.kt
  AOS/app/src/main/java/org/softeer/robocar/ui/adapter/PlaceSearchAdapter.kt
  AOS/app/src/main/java/org/softeer/robocar/ui/fragment/HeadcountDialogFragment.kt
  AOS/app/src/main/java/org/softeer/robocar/ui/fragment/InternalControlFragment.kt
  AOS/app/src/main/java/org/softeer/robocar/ui/fragment/PathSettingFragment.kt
  AOS/app/src/main/java/org/softeer/robocar/ui/fragment/SelectDestinationFragment.kt
  AOS/app/src/main/java/org/softeer/robocar/ui/viewmodel/MapViewModel.kt
  AOS/app/src/main/java/org/softeer/robocar/ui/viewmodel/PathSettingViewModel.kt
  AOS/app/src/main/res/layout/activity_map.xml
  AOS/app/src/main/res/layout/fragment_headcount_dialog.xml
  AOS/app/src/main/res/layout/fragment_path_setting.xml
  AOS/app/src/main/res/layout/fragment_select_destination.xml
  AOS/app/src/main/res/layout/item_place.xml
  AOS/app/src/main/res/navigation/bottom_sheet_nav_graph.xml
  AOS/app/src/main/res/values/strings.xml
Labels: 🌱 Feat

#132 [AOS] Mapactivity 기능추가
  AOS/app/src/main/java/org/softeer/robocar/data/model/Route.kt
  AOS/app/src/main/java/org/softeer/robocar/ui/activity/MapActivity.kt
  AOS/app/src/main/res/layout/activity_map.xml
Labels: 🌱 Feat

#134 [AOS] 푸시 로직 구현
  AOS/app/build.gradle.kts
  AOS/app/google-services.json
  AOS/app/src/main/AndroidManifest.xml
  AOS/app/src/main/java/org/softeer/robocar/data/dto/carpool/request/RejectCarPoolRequest.kt
  AOS/app/src/main/java/org/softeer/robocar/data/dto/carpool/request/RequestCarPoolRequest.kt
  AOS/app/src/main/java/org/softeer/robocar/data/dto/carpool/request/registerCarPoolRequest.kt
  AOS/app/src/main/java/org/softeer/robocar/data/dto/carpool/response/AcceptCarPoolResponse.kt
  AOS/app/src/main/java/org/softeer/robocar/data/dto/login/request/LoginRequest.kt
  AOS/app/src/main/java/org/softeer/robocar/data/mapper/CarPoolRequestMapper.kt
  AOS/app/src/main/java/org/softeer/robocar/data/model/Route.kt
  AOS/app/src/main/java/org/softeer/robocar/data/model/TaxiType.kt
  AOS/app/src/main/java/org/softeer/robocar/data/repository/CarPool/CarPoolRemoteDataSource.kt
  AOS/app/src/main/java/org/softeer/robocar/data/repository/CarPool/CarPoolRemoteDataSourceImpl.kt
  AOS/app/src/main/java/org/softeer/robocar/data/repository/CarPool/CarPoolRepository.kt
  AOS/app/src/main/java/org/softeer/robocar/data/repository/CarPool/CarPoolRepositoryImpl.kt
  AOS/app/src/main/java/org/softeer/robocar/data/repository/auth/AuthLocalDataSourceImpl.kt
  AOS/app/src/main/java/org/softeer/robocar/data/service/CarPool/CarPoolService.kt
  AOS/app/src/main/java/org/softeer/robocar/data/service/firebase/RoboCarFireBaseMessagingService.kt
  AOS/app/src/main/java/org/softeer/robocar/di/NetworkModule.kt
  AOS/app/src/main/java/org/softeer/robocar/di/RoboCarApplication.kt
  AOS/app/src/main/java/org/softeer/robocar/domain/usecase/AcceptCarPoolRequestUseCase.kt
  AOS/app/src/main/java/org/softeer/robocar/domain/usecase/GetCarPoolListUseCase.kt
  AOS/app/src/main/java/org/softeer/robocar/domain/usecase/RegisterCarPoolUseCase.kt
  AOS/app/src/main/java/org/softeer/robocar/domain/usecase/RejectCarPoolRequestUseCase.kt
  AOS/app/src/main/java/org/softeer/robocar/domain/usecase/RequestCarPoolUseCase.kt
  AOS/app/src/main/java/org/softeer/robocar/ui/activity/LoginActivity.kt
  AOS/app/src/main/java/org/softeer/robocar/ui/activity/RequestCarPoolActivity.kt
  AOS/app/src/main/java/org/softeer/robocar/ui/adapter/CarPoolBindingAdapter.kt
  AOS/app/src/main/java/org/softeer/robocar/ui/fragment/CarPoolCallFragment.kt
  AOS/app/src/main/java/org/softeer/robocar/ui/fragment/CarPoolListFragment.kt
  AOS/app/src/main/java/org/softeer/robocar/ui/fragment/CarPoolMatchingFragment.kt
  AOS/app/src/main/java/org/softeer/robocar/ui/fragment/CarPoolRejectDialogFragment.kt
  AOS/app/src/main/java/org/softeer/robocar/ui/fragment/CarPoolRequestDetailFragment.kt
  AOS/app/src/main/java/org/softeer/robocar/ui/fragment/CarPoolRequestDialogFragment.kt
  AOS/app/src/main/java/org/softeer/robocar/ui/fragment/ReceivedCarPoolRequestDialogFragment.kt
  AOS/app/src/main/java/org/softeer/robocar/ui/fragment/RideTypeSelectionFragment.kt
  AOS/app/src/main/java/org/softeer/robocar/ui/fragment/SelectDestinationFragment.kt
  AOS/app/src/main/java/org/softeer/robocar/ui/viewmodel/CarPoolDetailViewModel.kt
  AOS/app/src/main/java/org/softeer/robocar/ui/viewmodel/CarPoolListViewModel.kt
  AOS/app/src/main/java/org/softeer/robocar/ui/viewmodel/CarPoolMatchingViewModel.kt
  AOS/app/src/main/java/org/softeer/robocar/ui/viewmodel/MyPageViewModel.kt
  AOS/app/src/main/java/org/softeer/robocar/ui/viewmodel/ReceivedCarPoolRequestDialogViewModel.kt
  AOS/app/src/main/java/org/softeer/robocar/utils/interceptor/TokenInterceptor.kt
  AOS/app/src/main/res/layout/activity_request_car_pool.xml
  AOS/app/src/main/res/layout/fragment_car_pool_call.xml
  AOS/app/src/main/res/layout/fragment_car_pool_matching.xml
  AOS/app/src/main/res/layout/fragment_dialog_car_pool_reject.xml
  AOS/app/src/main/res/layout/fragment_dialog_received_car_pool_request.xml
  AOS/app/src/main/res/layout/fragment_ride_type_selection.xml
  AOS/app/src/main/res/layout/fragment_taxi_call.xml
  AOS/app/src/main/res/navigation/bottom_sheet_nav_graph.xml
  AOS/app/src/main/res/navigation/request_car_pool_nav_graph.xml
  AOS/app/src/main/res/values/strings.xml
  AOS/build.gradle.kts
Labels: 🌱 Feat

#137 [BE] 혼자타기 "/operations/optimized-route/solo" 생성
  BE/robocar/src/main/java/com/fiveguys/robocar/controller/OperationController.java
  BE/robocar/src/main/java/com/fiveguys/robocar/dto/res/RouteSoloResDto.java
  BE/robocar/src/main/java/com/fiveguys/robocar/repository/CarRepository.java
  BE/robocar/src/main/java/com/fiveguys/robocar/service/OperationService.java
Labels: 🌱 Feat

#147 [BE] onboard로 운행정보를 불러올수 있도록 기능 추가
  BE/robocar/src/main/java/com/fiveguys/robocar/controller/OperationController.java
  BE/robocar/src/main/java/com/fiveguys/robocar/dto/res/OnBoardDto.java
  BE/robocar/src/main/java/com/fiveguys/robocar/service/OperationService.java
Labels: 🌱 Feat

#138 [AOS] mapViewModel로 통합 / 차량,탑승유형 MapActivity로 받아오기
  AOS/app/src/main/java/org/softeer/robocar/data/model/PlaceItem.kt
  AOS/app/src/main/java/org/softeer/robocar/ui/activity/MapActivity.kt
  AOS/app/src/main/java/org/softeer/robocar/ui/activity/RequestCarPoolActivity.kt
  AOS/app/src/main/java/org/softeer/robocar/ui/fragment/PathSettingFragment.kt
  AOS/app/src/main/java/org/softeer/robocar/ui/fragment/TaxiInformationFragment.kt
  AOS/app/src/main/java/org/softeer/robocar/ui/viewmodel/MapViewModel.kt
  AOS/app/src/main/java/org/softeer/robocar/ui/viewmodel/PathSettingViewModel.kt
  AOS/app/src/main/java/org/softeer/robocar/ui/viewmodel/RouteViewModel.kt
  AOS/app/src/main/res/layout/fragment_taxi_information.xml
Labels: 🌱 Feat

#145 [AOS] TaxiType에 따른 차량 탑승 인원 제한 및 Dialog 버튼 활성/비활성화 구현
  AOS/app/src/main/java/org/softeer/robocar/ui/activity/MapActivity.kt
  AOS/app/src/main/java/org/softeer/robocar/ui/fragment/HeadcountDialogFragment.kt
  AOS/app/src/main/java/org/softeer/robocar/ui/fragment/SelectDestinationFragment.kt
  AOS/app/src/main/java/org/softeer/robocar/ui/viewmodel/MapViewModel.kt
  AOS/app/src/main/res/layout/fragment_headcount_dialog.xml
Labels: 🌱 Feat

#148 [AOS] 이벤트 발생에 따른 bottom sheet 상태 변경
  AOS/app/src/main/java/org/softeer/robocar/ui/activity/MapActivity.kt
  AOS/app/src/main/java/org/softeer/robocar/ui/fragment/PathSettingFragment.kt
  AOS/app/src/main/java/org/softeer/robocar/ui/fragment/SelectDestinationFragment.kt
  AOS/app/src/main/java/org/softeer/robocar/ui/viewmodel/MapViewModel.kt
  AOS/app/src/main/res/layout/activity_map.xml
Labels: 🌱 Feat

#151 [AOS] carPoolId값 mapActivity로 넘겨주기 구현
  AOS/app/src/main/java/org/softeer/robocar/data/model/CarPoolType.kt
  AOS/app/src/main/java/org/softeer/robocar/data/model/TaxiType.kt
  AOS/app/src/main/java/org/softeer/robocar/data/repository/auth/AuthRepository.kt
  AOS/app/src/main/java/org/softeer/robocar/data/repository/auth/AuthRepositoryImpl.kt
  AOS/app/src/main/java/org/softeer/robocar/ui/activity/MapActivity.kt
  AOS/app/src/main/java/org/softeer/robocar/ui/activity/RequestCarPoolActivity.kt
  AOS/app/src/main/java/org/softeer/robocar/ui/adapter/DataPassListener.kt
  AOS/app/src/main/java/org/softeer/robocar/ui/fragment/CarPoolCallFragment.kt
  AOS/app/src/main/java/org/softeer/robocar/ui/fragment/CarPoolListFragment.kt
  AOS/app/src/main/java/org/softeer/robocar/ui/fragment/CarPoolMatchingFragment.kt
  AOS/app/src/main/java/org/softeer/robocar/ui/fragment/CarPoolRejectDialogFragment.kt
  AOS/app/src/main/java/org/softeer/robocar/ui/fragment/CarPoolRequestDetailFragment.kt
  AOS/app/src/main/java/org/softeer/robocar/ui/fragment/CarPoolRequestDialogFragment.kt
  AOS/app/src/main/java/org/softeer/robocar/ui/fragment/HomeFragment.kt
  AOS/app/src/main/java/org/softeer/robocar/ui/fragment/MyPageFragment.kt
  AOS/app/src/main/java/org/softeer/robocar/ui/fragment/NoAvailableCarPoolFragment.kt
  AOS/app/src/main/java/org/softeer/robocar/ui/fragment/PathSettingFragment.kt
  AOS/app/src/main/java/org/softeer/robocar/ui/fragment/ReceivedCarPoolRequestDialogFragment.kt
  AOS/app/src/main/java/org/softeer/robocar/ui/fragment/RideTypeSelectionFragment.kt
  AOS/app/src/main/java/org/softeer/robocar/ui/fragment/SelectDestinationFragment.kt
  AOS/app/src/main/java/org/softeer/robocar/ui/viewmodel/CarPoolMatchingViewModel.kt
  AOS/app/src/main/java/org/softeer/robocar/ui/viewmodel/CarPoolRequestViewModel.kt
  AOS/app/src/main/java/org/softeer/robocar/ui/viewmodel/MapViewModel.kt
  AOS/app/src/main/java/org/softeer/robocar/ui/viewmodel/MyPageViewModel.kt
  AOS/app/src/main/java/org/softeer/robocar/ui/viewmodel/ReceivedCarPoolRequestDialogViewModel.kt
  AOS/app/src/main/res/layout/fragment_my_page.xml
  AOS/app/src/main/res/layout/fragment_no_available_car_pool.xml
  AOS/app/src/main/res/navigation/bottom_sheet_nav_graph.xml
  AOS/app/src/main/res/navigation/home_nav_graph.xml
  AOS/app/src/main/res/navigation/request_car_pool_nav_graph.xml
Labels: 🌱 Feat

#157 [ AOS] 앱 재실행 시, 운행정보 복구 구현
  AOS/app/src/main/java/org/softeer/robocar/data/dto/carpool/response/AcceptCarPoolResponse.kt
  AOS/app/src/main/java/org/softeer/robocar/data/repository/CarPool/CarPoolLocalDataSource.kt
  AOS/app/src/main/java/org/softeer/robocar/data/repository/CarPool/CarPoolLocalDataSourceImpl.kt
  AOS/app/src/main/java/org/softeer/robocar/data/repository/CarPool/CarPoolRemoteDataSource.kt
  AOS/app/src/main/java/org/softeer/robocar/data/repository/CarPool/CarPoolRemoteDataSourceImpl.kt
  AOS/app/src/main/java/org/softeer/robocar/data/repository/CarPool/CarPoolRepository.kt
  AOS/app/src/main/java/org/softeer/robocar/data/repository/CarPool/CarPoolRepositoryImpl.kt
  AOS/app/src/main/java/org/softeer/robocar/data/service/CarPool/CarPoolService.kt
  AOS/app/src/main/java/org/softeer/robocar/data/service/firebase/RoboCarFireBaseMessagingService.kt
  AOS/app/src/main/java/org/softeer/robocar/di/DataSourceModule.kt
  AOS/app/src/main/java/org/softeer/robocar/di/RepositoryModule.kt
  AOS/app/src/main/java/org/softeer/robocar/ui/activity/SplashActivity.kt
  AOS/app/src/main/java/org/softeer/robocar/ui/fragment/CarPoolRequestDialogFragment.kt
  AOS/app/src/main/java/org/softeer/robocar/ui/fragment/ReceivedCarPoolRequestDialogFragment.kt
  AOS/app/src/main/java/org/softeer/robocar/ui/viewmodel/CarPoolRequestDialogViewModel.kt
  AOS/app/src/main/java/org/softeer/robocar/ui/viewmodel/ReceivedCarPoolRequestDialogViewModel.kt
  AOS/app/src/main/java/org/softeer/robocar/ui/viewmodel/SplashViewModel.kt
Labels: 🌱 Feat
